### ISSUE TITLE
Valuzione riscrittura di radarcoordlib appoggiandosi su proj

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/radarcoordlib#1]
Seguito di discussione nata da [issue #9 su elaboradar](https://github.com/ARPA-SIMC/elaboradar/issues/9)

**Comment by spanezz** [comment]
Ho dato un'occhiata veloce. Se non mi son perso dei pezzi, geographiclib è usata solo in `RadarGeoCoord_util.cpp`, per passare da proiezione azimutale equidistante centrata sul radar a coordinate geografiche e viceversa. Se si vuol passare a proj, è una trasformazione che anche proj sa fare: http://www.remotesensing.org/geotiff/proj_list/azimuthal_equidistant.html

Detto questo, credo che la decisione debba essere presa in primo luogo da chi mantiene il codice: se non sbaglio, Davide Ori?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
